- menu_name: "Servicios"

- name: "Contactar"
  url: "/contact/"
  class: "services-contact"
  title: "Contactar"

- name: "RSS"
  url: "/feed.xml"
  class: "rss-link"
  title: "Subscribir RSS"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Sitemap para Google Webmaster Tools"
